
title: 打了三针疫苗的小张 #Your awesome title
email: zhangyuanrong62@gmail.com #youremail@domain.com
description: > # this means to ignore newlines until "baseurl"
  你好呀~

baseurl: # the subpath of the site
url: https://zhangyuanrong.github.io # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname
cusdis:
    app_id: #your cusdis app_id

user:
  name: 张源荣
  pic: /assets/img/cat.jpg
  picAlt: "catbook"
  job: 又是什么都记不住的一天
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
